Repository urbit/bridge, pull requests merged in 2021-06, with the labels that each got.

#571 network: get ecliptic & polls addresses from chain
  package.json
  src/lib/contracts.js
  src/store/network.js
Labels: code qol

#582 store: more nuanced syncing
  src/components/Passport.js
  src/lib/useSyncPoints.js
  src/store/lib/usePointStore.js
  src/views/Activate.js
  src/views/CreateGalaxy.js
  src/views/Invite/Cohort.js
  src/views/IssueChild.js
  src/views/Point.js
  src/views/Points.js
  src/views/Release/Active.js
Labels: code qol, performance

#587 store: finish syncOwnedPoint -> syncExtras rename
  src/views/AcceptTransfer.js
  src/views/Party/PartySetPoolSize.js
  src/views/UrbitOS/ChangeSponsor.js
Labels: bug

#584 deps: modernization and upgrades
  .eslintrc
  .nvmrc
  DEVELOPMENT.md
  config-overrides.js
  jsconfig.json
  package-lock.json
  package.json
  src/Bridge.js
  src/form/Inputs.js
  src/indigo-react/components/Input.js
  src/lib/SolarisClient.js
  src/lib/authToken.ts
  src/lib/constants.ts
  src/lib/flowCommand.ts
  src/lib/keys.js
  src/lib/reticket.js
  src/lib/router.js
  src/lib/tank.js
  src/lib/trezor.ts
  src/lib/txn.js
  src/lib/useIsEclipticOwner.js
  src/lib/usePermissionsForPoint.js
  src/lib/utils/address.test.ts
  src/lib/utils/address.ts
  src/lib/validators.js
  src/lib/wallet.js
  src/lib/wallet.ts
  src/react-app-env.d.ts
  src/store/lib/useControlledPointsStore.js
  src/store/lib/useResidentsStore.ts
  src/store/wallet.js
  src/views/AcceptLockup.js
  src/views/Activate/ActivateCode.js
  src/views/Activate/ActivatePassport.js
  src/views/CancelTransfer.js
  src/views/CreateGalaxy.js
  src/views/Login.tsx
  src/views/Login/Keystore.js
  src/views/Login/Ledger.tsx
  src/views/Login/Metamask.js
  src/views/Login/Mnemonic.js
  src/views/Login/PrivateKey.js
  src/views/Login/Ticket.js
  src/views/Login/Trezor.tsx
  src/views/Points.js
  src/views/Release/Transfer.js
  src/views/UrbitID/ResetKeys/ResetExecute.js
  src/views/UrbitID/SetProxy.js
  src/views/UrbitOS/NetworkingKeys.js
  tsconfig.json
Labels: code qol

#588 passport: include keyfile when available
  src/lib/invite.js
  src/views/Activate/ActivateCode.js
  src/views/Activate/PassportDownload.js
  src/views/UrbitID/DownloadKeys.js
Labels: networking keys
